package com.sdd.exporters;

import com.sdd.core.TestCaseModel;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.List;
import java.util.stream.Collectors;

/**
 * GherkinExporter - Converts test cases to Cucumber .feature files.
 */
public class GherkinExporter {

    public static void export(List<TestCaseModel> tcs, String dir, String ticketId) throws Exception {
        new File(dir).mkdirs();
        write(tcs, "UI",            dir, ticketId + "_UI_Tests.feature");
        write(tcs, "API",           dir, ticketId + "_API_Tests.feature");
        write(tcs, "ACCESSIBILITY", dir, ticketId + "_Accessibility_Tests.feature");
        System.out.println("Gherkin .feature files exported: " + dir);
    }

    private static void write(List<TestCaseModel> all, String type, String dir, String fname) throws Exception {
        List<TestCaseModel> filtered = all.stream().filter(t -> t.getType().equals(type)).collect(Collectors.toList());
        if (filtered.isEmpty()) return;
        String ticketId = filtered.get(0).getTicketId();

        try (PrintWriter pw = new PrintWriter(new FileWriter(dir + "/" + fname))) {
            pw.println("# ================================================");
            pw.println("# AUTO-GENERATED BY SDD FRAMEWORK");
            pw.println("# Ticket: " + ticketId + " | Type: " + type + " | Count: " + filtered.size());
            pw.println("# ================================================");
            pw.println();
            pw.println("Feature: " + type + " Tests for " + ticketId);
            pw.println("  As a QA Engineer validating " + ticketId);
            pw.println("  I want to verify all " + type.toLowerCase() + " requirements");
            pw.println("  So that the application meets the specification");
            pw.println();

            for (TestCaseModel tc : filtered) {
                pw.println("  # " + tc.getTcId() + " | " + tc.getRequirementId());
                pw.println("  # AC: " + tc.getOriginalAC());
                pw.println("  @" + tc.getTcId() + " @" + type.toLowerCase() +
                    " @" + tc.getPriority().toLowerCase() + " @" + ticketId);
                pw.println("  Scenario: " + tc.getTitle());
                switch (type) {
                    case "UI" -> {
                        pw.println("    Given the application is running and accessible");
                        pw.println("    And the user is on the relevant page");
                        pw.println("    When the user performs action: \"" + safe(tc.getTitle()) + "\"");
                        pw.println("    Then the system should respond as expected");
                        pw.println("    And the result should match: \"" + safe(tc.getExpectedResult()) + "\"");
                    }
                    case "API" -> {
                        pw.println("    Given the API server is running");
                        pw.println("    And valid authentication headers are set");
                        pw.println("    When the API request is sent for: \"" + safe(tc.getTitle()) + "\"");
                        pw.println("    Then the response status code should be valid");
                        pw.println("    And the response body should match: \"" + safe(tc.getExpectedResult()) + "\"");
                    }
                    case "ACCESSIBILITY" -> {
                        pw.println("    Given the application page is loaded in browser");
                        pw.println("    When the accessibility scan is run with WCAG AA tags");
                        pw.println("    Then there should be zero critical violations");
                        pw.println("    And the page should comply with: \"" + safe(tc.getTitle()) + "\"");
                    }
                }
                pw.println();
            }
        }
    }

    private static String safe(String s) {
        if (s == null) return "";
        return s.replace("\"", "'").replace("\n", " ").trim();
    }
}
