# AUTO-GENERATED BY SDD FRAMEWORK | Ticket: PROJ-101 | Type: API
Feature: API Tests for PROJ-101
  As a QA Engineer validating PROJ-101
  I want to verify all API requirements
  So that the backend services meet the specification

  # API-TC-001 | PROJ-101-AP-REQ-001
  @API-TC-001 @api @critical @PROJ-101
  Scenario: Validate API: POST /api/login returns 200 with JWT token
    Given the API server is running
    And valid authentication headers are set
    When I send POST "/api/login" with valid credentials
    Then the response status should be 200
    And the response body should contain "token"

  # API-TC-002 | PROJ-101-AP-REQ-002
  @API-TC-002 @api @critical @PROJ-101
  Scenario: Validate API: POST /api/login returns 401 for invalid credentials
    Given the API server is running
    And valid authentication headers are set
    When I send POST "/api/login" with invalid credentials
    Then the response status should be 401

  # API-TC-003 | PROJ-101-AP-REQ-003
  @API-TC-003 @api @high @PROJ-101
  Scenario: Validate API: GET /api/users returns 200 with user list
    Given the API server is running
    And valid authentication headers are set
    When I send GET "/api/users"
    Then the response status should be 200
